### ISSUE TITLE
Problem with code

### ISSUE THREAD

**Issue by LukStanczak** [misaelzapata/CodeIgniter-Inline-Images-Email#10]
Hi. I have problem with add image to html code.

That is my code:
-------------------------------------------------------
$from = 'staniuxxx@gmail.com';
        $to = 'test@gmail.com;
        $subject = 'Potwierdzenie rejestracji';

        $text = '<html><head><title>Tytuł</title></head><body>tekst z obrazkiem <br />< img src="cid:assets/img/Wykres.jpg" border="0" ></body></html>';

        if ($this->mail->sendmail($from, $to, $subject, $text, 'assets/img/Wykres.jpg')) {
          $this->load->view('signup_successful');
        }
----------------------------------------------------------
and liblary:

----------------------
    function sendmail($from = NULL, $to = NULL, $subject = NULL, $text = NULL, $filepath = NULL) {
        $CI =& get_instance();
        $CI->load->library('email');
        $CI->email->set_newline("\r\n");

        $CI->email->from($from);
        $CI->email->to($to);
        $CI->email->subject($subject);
        $CI->email->message($text);
        if ($filepath) { //jeżeli chcemy wysłać załącznik
            $path = $CI->config->item('server_root'); 
            $file = $path . $filepath; 
            $CI->email->attach($file , "inline");
        }
        $CI->email->send();
        echo $CI->email->print_debugger();
-------------------------------------

in mail I have:
---------------

tekst z obrazkiem 
< img src="cid:inl_0" border="0" >

-----------------------
and that is in debugger:

--------------

--B_ALT_562e6f10d2827
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

tekst z obrazkiem < img src="cid:inl_0" border="0" >

--B_ALT_562e6f10d2827
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html><head><title>TytuĹ</title></head><body>tekst z obrazkiem <br />< img=
 src=3D"cid:inl_0" border=3D"0" ></body></html>

--B_ALT_562e6f10d2827--

--B_ATC_562e6f10d282e
Content-type: image/jpeg; name="Wykres.jpg"
Content-Disposition: inline;
Content-Transfer-Encoding: base64
Content-ID: <inl_0>

What i do wrong, please gave me some hint

**Comment by avido** [comment]
The library is using the basename as replacement so instead of "cid:assets/img/Wykres.jpg" use cid:Wykres.jpg" instead..
