### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by zur4ik** [misaelzapata/CodeIgniter-Inline-Images-Email#11]
Using CI 3 faced this error:
`Message: Undefined property: MY_Email::$_attach_name`

**Comment by Ema4rl** [comment]
CI 3 has this functionality by default. Check the [CI_Email::attachment_cid Documentation](https://www.codeigniter.com/user_guide/libraries/email.html#CI_Email::attachment_cid).

**Comment by zur4ik** [comment]
@Ema4rl I already found solution. Looks like it was required to attach file with another method and then just get `CID`.  Thanks anyway.
