### ISSUE TITLE
What to place within the HTML

### ISSUE THREAD

**Issue by internetmedianl** [misaelzapata/CodeIgniter-Inline-Images-Email#7]
Hi there,
In your instruction you said "Then in the email view add this:". The only problem is that the image you referred to does not work anymore. 

Could you please tell me what code I should you within the HTML?
Thanks a lot in advance!

**Comment by sidaurukfreddy** [comment]
I just read and try again over and over and failed, what do wrong ?
honestly i success attachment images without My_Email.php then i put that library in my folder filbrary and get errors Message: Use of undefined constant file_name - assumed 'file_name' 

am trying to load library in autoload.php but nothing progress, please tell me where is wriong ?

Thankd in advance

$autoload['libraries'] = array('MY_Email');

**Comment by misaelzapata** [comment]
Hi @sidaurukfreddy, did you read the docs of CI? please take a look at this:
http://www.codeigniter.com/userguide2/general/creating_libraries.html go straight to "Extending Native Libraries", and as commented in the email I sent you, if you are using CI 3.0 it won't work. This is not an issue of the library.

**Comment by sidaurukfreddy** [comment]
So is there another solutions for CI 3 Misael, i'm new bie at this case, Thanks
